x-service-templates:
  go-backend: &go-backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payment-processor
    depends_on:
      - redis
      - mongodb

services:
  go-backend-1:
    <<: *go-backend
    container_name: go-backend-1
    ports:
      - "9091:80"
    environment:
    - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    - PORT=80
    - REDIS_ADDR=redis-db:6379
    - MONITOR_HEALTH=true
    - ENABLE_PROFILING=false
    - MONGO_ENDPOINT=mongodb://mongodb:27017
    - MONGO_DATABASE=payments-db
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "85MB"

  go-backend-2:
    <<: *go-backend
    container_name: go-backend-2
    ports:
      - "9092:80"
    environment:
    - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    - PORT=80
    - REDIS_ADDR=redis-db:6379
    - MONITOR_HEALTH=false
    - ENABLE_PROFILING=false
    - MONGO_ENDPOINT=mongodb://mongodb:27017
    - MONGO_DATABASE=payments-db
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "85MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis-db
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - app
      - payment-processor
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  mongodb:
    container_name: mongodb
    image: mongo:8.0.11
    ports:
      - "27017:27017"
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  load-balancer:
    container_name: load-balancer-nginx
    image: nginx:1.27.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-backend-1
      - go-backend-2
    ports:
      - "9999:9999"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  # In the browser:
  # Default User: admin
  # Default Password: pass
  mongo_express:
    container_name: mongo-ui
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always
    networks:
      - app

networks:
  app:
    driver: bridge
  payment-processor:
    external: true