x-service-templates:
  go-backend: &go-backend
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - payment-processor

services:
  go-backend-1:
    <<: *go-backend
    container_name: go-backend-1
    ports:
      - "9091:80"
    environment:
    - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    - PORT=80
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  go-backend-2:
    <<: *go-backend
    container_name: go-backend-2
    ports:
      - "9092:80"
    environment:
    - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    - PORT=80
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  load-balancer:
    container_name: load-balancer-nginx
    image: nginx:1.27.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-backend-1
      - go-backend-2
    ports:
      - "9999:9999"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true