# /etc/nginx/nginx.conf

#################
## Global Section
#################
load_module modules/ngx_otel_module.so;

worker_processes auto;
worker_rlimit_nofile 500000;

events {
    use epoll;
    worker_connections 512;
}

http {
    include       mime.types;  # if needed
    default_type  application/octet-stream;

    access_log off;

    # Pull in your OpenTelemetry tracing configuration
    include /etc/nginx/conf.d/opentelemetry_module.conf;

    # Ensure tracing is enabled and context will propagate
    otel_trace on;
    otel_trace_context propagate;

    upstream api {
        server go-backend-1:80;
        server go-backend-2:80;
        keepalive 200;
    }

    server {
        listen 9999;

        location / {
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Keep-Alive "";
            proxy_set_header Proxy-Connection "keep-alive";
            proxy_set_header Host $host;
            
            proxy_pass http://api;
        }
    }
}
