# /etc/nginx/opentelemetry_module.conf
#
# OpenTelemetry configuration for exporting trace data
#
# Must be inside the `http` block.

# Default service name used in Jaeger for NGINX spans.
otel_service_name nginx-lb;

otel_exporter {
    endpoint jaeger:4317;
    interval 5s;
    batch_size 512;
    batch_count 4;
}
